Feature: NHS Costs Checker Tool Test

  @NHSTest
  Scenario Outline: To know what help I can get with my NHS costs as a person from Wales
    Given am a person from Wales
      | Browser   |
      | <browser> |
    When I put my circumstances into the Checker tool
      | RegisterGPNotInEngland   | DentalPracticeReg  | Day   | Month   | Year   | LiveWithPartner   | YouOrYourPernerCLaimBenefits   | pregnantInLastTwelveMonths   | InjuryOrIllnessCaused   | HaveDiabetes   | HaveGlaucoma   | PermanentlyInCareHome   | HelpToPayForCareHome   | HaveSavingsInvestmentsProperty   |YourPartnerGetUniversalCredit   | JointUniversalCredit   | CombinedTakeHomePay   | TaxCredits   | IncomeSupp   | EmployeeSupportAllowance   | JobSeekerAllowance   | PersonalCredits   | NoWeDontGetAny   | WorkTaxAndChildTaxCredit   | WorkTaxDisabilityElement   | WorkTaxCredit   | ChildTaxCredit   | IncomeRelatedESA   | ContributionBasedESA   | IncomeRelatedJSA   | ContributionBasedJSA   | GuaranteeCredit   | GuaranteeAndSavingsCredit   | SavingsCreditMax   |
      | <registerGPNotInEngland> | <dentalPracticeReg>| <day> | <month> | <year> | <liveWithPartner> | <youOrYourPernerCLaimBenefits> | <pregnantInLastTwelveMonths> | <injuryOrIllnessCaused> | <haveDiabetes> | <haveGlaucoma> | <permanentlyInCareHome> | <helpToPayForCareHome> | <haveSavingsInvestmentsProperty> |<yourPartnerGetUniversalCredit> | <jointUniversalCredit> | <combinedTakeHomePay> | <taxCredits> | <incomeSupp> | <employeeSupportAllowance> | <jobSeekerAllowance> | <personalCredits> | <noWeDontGetAny> | <workTaxAndChildTaxCredit> | <workTaxDisabilityElement> | <workTaxCredit> | <childTaxCredit> | <incomeRelatedESA> | <contributionBasedESA> | <incomeRelatedJSA> | <contributionBasedJSA> | <guaranteeCredit> | <guaranteeAndSavingsCredit> | <savingsCreditMax> |
    Then I should get a result of whether I will get help or not
    Examples:
      | browser   | registerGPNotInEngland | dentalPracticeReg   | day | month | year | liveWithPartner | youOrYourPernerCLaimBenefits | pregnantInLastTwelveMonths  | injuryOrIllnessCaused | haveDiabetes  | haveGlaucoma | permanentlyInCareHome | helpToPayForCareHome | haveSavingsInvestmentsProperty | yourPartnerGetUniversalCredit | jointUniversalCredit | combinedTakeHomePay | taxCredits | incomeSupp | employeeSupportAllowance | jobSeekerAllowance | personalCredits | noWeDontGetAny | workTaxAndChildTaxCredit | workTaxDisabilityElement | workTaxCredit | childTaxCredit | incomeRelatedESA | contributionBasedESA | incomeRelatedJSA | contributionBasedJSA | guaranteeCredit | guaranteeAndSavingsCredit | savingsCreditMax |
      | Chrome    | Yes                    | Wales               | 11  | 11    | 1999 | Yes             | Yes                          |                             |                       |               |              |                       |                      |                                | Yes                           | No                   | Yes                 |            |            |                          |                    |                 |                |                          |                          |               |                |                  |                      |                  |                      |                 |                           |                  |
      | firefox   | No                     | I am not registered | 12  | 12    | 1999 | No              | No                           | Yes                         |  Yes                  | Yes           | Yes          |  Yes                  |  No                  |   Yes                          |                               |                      |                     |            |            |                          |                    |                 |                |                          |                          |               |                |                  |                      |                  |                      |                 |                           |                  |


